### ISSUE TITLE
java.lang.NoClassDefFoundError: oauth.signpost.basic.DefaultOAuthConsumer

### ISSUE THREAD

**Issue by devilabhi2** [mukesh4u/Android-LinkedIn-Demo#4]
Thanks for your tutorial. I am following your tutorial to get profile details from linkedin profile. I am getting a crash at line 'LinkedinDialog.liToken = LinkedinDialog.oAuthService.getOAuthRequestToken(OAUTH_CALLBACK_URL);' in 'LinkedinDialog' class

I clicked on linkedin button in [this](http://paste.ofcode.org/gZtrghTqRQvjL5dvqTteDd) class and took LinkedinDialog in another class, code for [LinkedinDialog](http://paste.ofcode.org/t3guuP6sjTG3SaDXW2uGXW)

The jar files i am using are linkedin-j-android.jar and signpost-core-1.2.1.2.jar

Logcat is: 

java.lang.NoClassDefFoundError: oauth.signpost.basic.DefaultOAuthConsumer
            at com.google.code.linkedinapi.client.oauth.LinkedInOAuthServiceImpl.getOAuthConsumer(LinkedInOAuthServiceImpl.java:246)
            at com.google.code.linkedinapi.client.oauth.LinkedInOAuthServiceImpl.getOAuthRequestToken(LinkedInOAuthServiceImpl.java:169)
            at com.codebrew.learnrlink.utils.LinkedinDialog.setWebView(LinkedinDialog.java:76)
            at com.codebrew.learnrlink.utils.LinkedinDialog.onCreate(LinkedinDialog.java:65)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:355)
            at android.app.Dialog.show(Dialog.java:260)
            at com.codebrew.learnrlink.fragments.ProfileFragment.linkedInLogin(ProfileFragment.java:927)
            at com.codebrew.learnrlink.fragments.ProfileFragment.onClick(ProfileFragment.java:422)
            at android.view.View.performClick(View.java:4211)
            at android.view.View$PerformClick.run(View.java:17446)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5297)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mukesh4u** [comment]
can you please update the jar and use this one
http://code.google.com/p/oauth-signpost/downloads/detail?name=signpost-commonshttp4-1.2.1.1.jar&can=2&q=

**Comment by devilabhi2** [comment]
i used these and after using these the project don't run. Ok, if you say lemme try again

**Comment by devilabhi2** [comment]
can you please give the link of all jars you used, may be it is due to jar files problem?

**Comment by amitsharmahimcs** [comment]
you have need some thing or what ...?

On Wed, May 20, 2015 at 12:04 PM, devilabhi2 <notifications@github.com>
wrote:

> can you please give the link of all jars you used, may be it is due to jar
> files problem?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mukesh4u/Android-LinkedIn-Demo/issues/4#issuecomment-103778621>
> .
>



-- 
   Dear,
           Sir/Mam This is amit kumar sharma.

*      Regards*
*Amit Kumar Sharma*
*+919015605797,+917042757449

**Comment by devilabhi2** [comment]
can you tell how you did that, if you have demo project then can you please give

**Comment by amitsharmahimcs** [comment]
i don't understand  what you exactly you want what kind of project you want from me can you explain ...... then i will send you ...

**Comment by amitsharmahimcs** [comment]
mukesh are you talking about quickblox ..... Do it your self i have expence
my time on RND then i find all 1 week i expend then i got all the thing so
do it your self all the things are given in SDK or Updated sdk and code all
the things are given here and one another thing you have need to manage
users from admin side ......

On Wed, May 20, 2015 at 7:15 PM, devilabhi2 <notifications@github.com>
wrote:

> can you tell how you did that, if you have demo project then can you
> please give
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mukesh4u/Android-LinkedIn-Demo/issues/4#issuecomment-103893515>
> .
>



-- 
   Dear,
           Sir/Mam This is amit kumar sharma.

*      Regards*
*Amit Kumar Sharma*
*+919015605797,+917042757449

**Comment by amitsharmahimcs** [comment]
It will solve before a sdk which one i have Dun my own RND where i found
some errors in sdk so let you update his api or Library files updated use
... it will solve ....

On Thu, May 21, 2015 at 11:03 AM, Amit Sharma <amit.sharma.himcs@gmail.com>
wrote:

> mukesh are you talking about quickblox ..... Do it your self i have
> expence my time on RND then i find all 1 week i expend then i got all the
> thing so do it your self all the things are given in SDK or Updated sdk and
> code all the things are given here and one another thing you have need to
> manage users from admin side ......
>
> On Wed, May 20, 2015 at 7:15 PM, devilabhi2 <notifications@github.com>
> wrote:
>
>> can you tell how you did that, if you have demo project then can you
>> please give
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mukesh4u/Android-LinkedIn-Demo/issues/4#issuecomment-103893515>
>> .
>>
>
>
>
> --
>    Dear,
>            Sir/Mam This is amit kumar sharma.
>
> *      Regards*
> *Amit Kumar Sharma*
> *+919015605797,+917042757449
>
>


-- 
   Dear,
           Sir/Mam This is amit kumar sharma.

*      Regards*
*Amit Kumar Sharma*
*+919015605797,+917042757449

**Comment by devilabhi2** [comment]
@amitsharmahimcs  I followed mario linkedin api and able to get basic profile details, but I am unable to get email-address, currently trying to get that

**Comment by amitsharmahimcs** [comment]
mukesh this is short hind for geting emailid of login user

LinkedinDialog d = new LinkedinDialog(LinkedInSampleActivity.this,
progressDialog);
d.show();

// set call back listener to get oauth_verifier value
d.setVerifierListener(new OnVerifyListener() {
@Override
public void onVerify(String verifier) {
try {

accessToken = LinkedinDialog.oAuthService
.getOAuthAccessToken(LinkedinDialog.liToken,
verifier);
LinkedinDialog.factory.createLinkedInApiClient(accessToken);
client = factory.createLinkedInApiClient(accessToken);


Person p = client.getProfileForCurrentUser();

p.getMainAddress()
} catch (Exception e) {
Log.i("LinkedinSample", "error to get verifier");
e.printStackTrace();
}
}

On Thu, May 21, 2015 at 2:46 PM, devilabhi2 <notifications@github.com>
wrote:

> @amitsharmahimcs <https://github.com/amitsharmahimcs> I followed mario
> linkedin api and able to get basic profile details, but I am unable to get
> email-address, currently trying to get that
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mukesh4u/Android-LinkedIn-Demo/issues/4#issuecomment-104190899>
> .
>



-- 
   Dear,
           Sir/Mam This is amit kumar sharma.

*      Regards*
*Amit Kumar Sharma*
*+919015605797,+917042757449

**Comment by devilabhi2** [comment]
can you give any working demo project of this?

**Comment by amitsharmahimcs** [comment]
this is login code i think i have use your code which is uploaded by you i
think i am not sure to know that this code is for your or some one else
code i was use only before 2 or 3 month ago to integrate with all social
sites integration .... if you face some other problem then tell me
may be i can help you to do any thing with you ....etc ...

On Thu, May 21, 2015 at 5:12 PM, Amit Sharma <amit.sharma.himcs@gmail.com>
wrote:

> mukesh this is short hind for geting emailid of login user
>
> LinkedinDialog d = new LinkedinDialog(LinkedInSampleActivity.this,
> progressDialog);
> d.show();
>
> // set call back listener to get oauth_verifier value
> d.setVerifierListener(new OnVerifyListener() {
> @Override
> public void onVerify(String verifier) {
> try {
>
> accessToken = LinkedinDialog.oAuthService
> .getOAuthAccessToken(LinkedinDialog.liToken,
> verifier);
> LinkedinDialog.factory.createLinkedInApiClient(accessToken);
> client = factory.createLinkedInApiClient(accessToken);
>
>
> Person p = client.getProfileForCurrentUser();
>
> p.getMainAddress()
> } catch (Exception e) {
> Log.i("LinkedinSample", "error to get verifier");
> e.printStackTrace();
> }
> }
>
> On Thu, May 21, 2015 at 2:46 PM, devilabhi2 <notifications@github.com>
> wrote:
>
>> @amitsharmahimcs <https://github.com/amitsharmahimcs> I followed mario
>> linkedin api and able to get basic profile details, but I am unable to get
>> email-address, currently trying to get that
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mukesh4u/Android-LinkedIn-Demo/issues/4#issuecomment-104190899>
>> .
>>
>
>
>
> --
>    Dear,
>            Sir/Mam This is amit kumar sharma.
>
> *      Regards*
> *Amit Kumar Sharma*
> *+919015605797,+917042757449
>
>


-- 
   Dear,
           Sir/Mam This is amit kumar sharma.

*      Regards*
*Amit Kumar Sharma*
*+919015605797,+917042757449

**Comment by devilabhi2** [comment]
I am unable to get email address using mario code.

**Comment by amitsharmahimcs** [comment]
mukesh have already given here in code all the things so let you have to implement to do it it will solve try by it self

**Comment by mukesh4u** [comment]
Hello Friends, I fixed above issue and update the code please check the latest code
